-- GENERADO POR scripts/generate-seed-sql.mjs — no editar a mano.
-- Fuente de verdad: server/seed.js (transcripción del cuaderno del cliente).
-- Regenerar con: npm run db:generate

INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p1', 'despertar-sencillo', 'Despertar Sencillo', 50000, NULL, 'clasicos', 'El primer desayuno de la casa. Panqueques, jugo y una nota escrita a mano.', 'Nuestro desayuno de entrada: mini panqueques recién hechos con miel, jugo de naranja exprimido esa misma mañana y fruta cortada al momento. Va con cubiertos, servilleta de tela y una tarjeta que escribimos a mano con tu mensaje.', 1, 'Se arma la madrugada de la entrega. Pedidos hasta las 8:00 p. m. del día anterior.', '["/img/french-toast-banano.jpg","/img/jugo-naranja.jpg","/img/yogurt-granola.jpg"]', '[{"name":"Jugo de naranja natural","detail":"350 ml, exprimido el mismo día"},{"name":"Mini panqueques con miel","detail":"4 unidades"},{"name":"Fruta de temporada","detail":"corte del día"},{"name":"Mermelada y mantequilla","detail":"porción individual"},{"name":"Cubiertos y servilleta","detail":"incluidos"},{"name":"Tarjeta personalizada","detail":"escrita a mano con tu mensaje"}]', '["Más vendido"]', '[]', 1, 1, 0);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p2', 'manana-dulce', 'Mañana Dulce', 60000, NULL, 'dulces', 'Yogurt griego, fresa, kiwi y galleta artesanal.', 'Para quien prefiere empezar liviano pero con azúcar honesta: yogurt griego con fresa y kiwi frescos, galleta artesanal horneada por una panadería del barrio y jugo de naranja.', 1, 'Viaja en frío hasta tu puerta.', '["/img/yogurt-granola.jpg","/img/smoothie-fresa.jpg","/img/bowl-frutas-coco.jpg"]', '[{"name":"Jugo de naranja natural","detail":"350 ml"},{"name":"Yogurt griego","detail":"vaso de 200 g"},{"name":"Fresas y kiwi","detail":"cortados al momento"},{"name":"Galleta artesanal","detail":"horneada el mismo día"}]', '[]', '[]', 1, 1, 1);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p3', 'zen-morning', 'Zen Morning', 65000, NULL, 'saludables', 'Jugo verde, tostadas de aguacate y frutos secos.', 'El desayuno de los que entrenan temprano. Jugo verde de espinaca, manzana y pepino; tostadas de pan de masa madre con aguacate; frutos secos y una tabla de fruta con kiwi, piña y arándanos.', 1, 'El jugo verde se hace 40 minutos antes de salir.', '["/img/aguacate-huevo-dark.jpg","/img/bowl-aguacate.jpg","/img/bowl-frutas-azul.jpg"]', '[{"name":"Jugo verde","detail":"espinaca, manzana y pepino · 350 ml"},{"name":"Tostadas de aguacate","detail":"2 unidades en masa madre"},{"name":"Frutos secos","detail":"almendra, marañón y nuez"},{"name":"Fruta fresca","detail":"kiwi, piña y arándanos"}]', '["Sin azúcar añadida"]', '[]', 1, 1, 2);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p4', 'desayuno-mini-explorador', 'Desayuno Mini Explorador', 70000, NULL, 'infantiles', 'Panqueques con chispas, brocheta de frutas y una sorpresa adentro.', 'Pensado para niños. Panqueques con toppings a elegir (miel, chispas de chocolate, rodajas de banano), brocheta de frutas, jugo, un yogurt pequeño y una sorpresa escondida en la caja.', 1, 'Cuéntanos la edad en las notas del pedido y ajustamos la sorpresa.', '["/img/french-toast-banano.jpg","/img/banano-rosa.jpg","/img/jugo-naranja.jpg"]', '[{"name":"Panqueques","detail":"4 unidades"},{"name":"Toppings","detail":"miel, chispas de chocolate y banano en rodajas"},{"name":"Brocheta de frutas","detail":"2 unidades"},{"name":"Jugo","detail":"250 ml"},{"name":"Yogurt pequeño","detail":"150 g"},{"name":"Sorpresa","detail":"juguete o dulce sorpresa según edad"}]', '["Para niños"]', '[]', 0, 1, 3);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p5', 'cesta-campestre', 'Cesta Campestre', 75000, NULL, 'clasicos', 'Panadería, queso campesino, waffle integral y té.', 'Una cesta larga para desayunar sin prisa: pan integral, croissant, waffle integral, queso campesino, buñuelitos, fruta fresca con kiwi, fresa y mango, y una selección de tés.', 2, 'Va en cesta de mimbre que se queda con quien lo recibe.', '["/img/waffles-frutas.jpg","/img/panes-artesanales.jpg","/img/tostada-huevo.jpg"]', '[{"name":"Jugo natural","detail":"350 ml"},{"name":"Pan integral y croissant","detail":"de panadería local"},{"name":"Waffle integral","detail":"1 unidad"},{"name":"Queso campesino","detail":"porción de 150 g"},{"name":"Fruta fresca","detail":"kiwi, fresa y mango"},{"name":"Selección de tés","detail":"3 sobres"},{"name":"Buñuelitos","detail":"4 unidades"}]', '["Alcanza para dos"]', '[]', 1, 1, 4);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p6', 'detox-box', 'Detox Box', 80000, 92000, 'saludables', 'Jugo de coco y jengibre, shot de limón, granola y cítricos.', 'La caja de los lunes. Jugo de coco con jengibre y limón, frutas cítricas, yogurt griego con granola, un shot de jengibre y limón, galleta integral de avena y bolitas de queso.', 1, 'El shot viaja aparte, en botella sellada.', '["/img/bowl-frutas-coco.jpg","/img/bowl-frutas-azul.jpg","/img/smoothie-fresa.jpg"]', '[{"name":"Jugo de coco, jengibre y limón","detail":"350 ml"},{"name":"Frutas cítricas","detail":"naranja, mandarina y toronja"},{"name":"Yogurt griego con granola","detail":"200 g"},{"name":"Shot de jengibre y limón","detail":"60 ml"},{"name":"Galleta integral de avena","detail":"2 unidades"},{"name":"Bolitas de queso","detail":"4 unidades","needsReview":true}]', '["Sin azúcar añadida"]', '[]', 0, 1, 5);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p7', 'amanecer-romantico', 'Amanecer Romántico', 90000, NULL, 'romanticos', 'Fresas con crema, croissants rellenos de chocolate y jugo de frutos rojos.', 'El desayuno de aniversario. Jugo de frutos rojos y jugo de naranja, fresas con crema, croissants rellenos de chocolate, tabla de quesos y uvas verdes. Se puede pedir con globo y vela.', 2, 'Se entrega con tarjeta manuscrita. Globo y vela se agregan como adicionales.', '["/img/croissant.jpg","/img/smoothie-fresa.jpg","/img/bowl-frutas-coco.jpg"]', '[{"name":"Jugo de frutos rojos","detail":"350 ml"},{"name":"Jugo de naranja","detail":"350 ml"},{"name":"Fresas con crema","detail":"copa de 250 g"},{"name":"Croissants rellenos de chocolate","detail":"2 unidades"},{"name":"Tabla de quesos","detail":"3 quesos"},{"name":"Uvas verdes","detail":"racimo"}]', '["Para dos"]', '[]', 1, 1, 6);
INSERT OR IGNORE INTO products (id, slug, name, price, compare_at, category, tagline, description, serves, prep_note, images, includes, badges, reviews, featured, active, position) VALUES ('p8', 'brunch-gourmet', 'Brunch Gourmet', 100000, 115000, 'gourmet', 'Dos jugos, tabla de galletas y quesos, avena con tocineta.', 'El más completo de la carta. Dos jugos, tabla de galletas y quesos, avena con tocineta, fruta fresca, uvas y arándanos, y bolitas de queso. Alcanza cómodo para dos personas.', 2, 'La avena viaja en termo para llegar caliente.', '["/img/tostada-huevo.jpg","/img/waffles-frutas.jpg","/img/panes-artesanales.jpg"]', '[{"name":"Dos jugos naturales","detail":"350 ml cada uno"},{"name":"Tabla de galletas y quesos","detail":"4 quesos"},{"name":"Avena con tocineta","detail":"porción caliente","needsReview":true},{"name":"Fruta fresca","detail":"corte del día"},{"name":"Uvas y arándanos","detail":"porción"},{"name":"Bolitas de queso","detail":"6 unidades","needsReview":true}]', '["El más completo"]', '[]', 0, 1, 7);

INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a1', 'Globo metalizado', 12000, 'detalle', '/img/banano-rosa.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a2', 'Ramo de flores pequeño', 35000, 'detalle', '/img/smoothie-fresa.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a3', 'Jugo extra', 8000, 'comida', '/img/jugo-naranja.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a4', 'Croissant relleno de chocolate', 9000, 'comida', '/img/croissant.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a5', 'Porción extra de fruta', 10000, 'comida', '/img/bowl-frutas-coco.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a6', 'Vela y fósforos', 6000, 'detalle', '/img/banano-rosa.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a7', 'Café de origen (250 g)', 28000, 'detalle', '/img/panes-artesanales.jpg', 1);
INSERT OR IGNORE INTO addons (id, name, price, category, image, active) VALUES ('a8', 'Segundo puesto (repite el desayuno)', 32000, 'comida', '/img/waffles-frutas.jpg', 1);

INSERT OR IGNORE INTO posts (id, slug, title, excerpt, cover, author, date, body, published) VALUES ('b1', 'como-armamos-una-caja', 'Cómo armamos una caja a las 4 de la mañana', 'La fruta se corta a las 4:10. El jugo se exprime a las 4:40. La tarjeta se escribe de último, para que la tinta no se corra.', '/img/tabla-ingredientes.jpg', 'Equipo Aurora', '2026-07-28', 'La cocina abre a las 3:40 a. m. No es romanticismo: un desayuno que sale a las 6:00 tiene que armarse en ese orden exacto o llega tibio.

Primero la fruta. Se corta entera, nunca la noche anterior, porque la piña suelta agua y moja la galleta. Después el pan: lo recogemos de la panadería de la esquina a las 4:30, todavía caliente.

El jugo va de último entre los líquidos. Exprimido a las 4:40, sellado a las 4:45, en frío hasta que sube al carro.

La tarjeta se escribe al final. Con tinta de gel, que seca rápido, y siempre a mano. Es lo primero que lee quien abre la caja.', 1);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, cover, author, date, body, published) VALUES ('b2', 'que-regalar-segun-la-ocasion', 'Qué desayuno regalar según la ocasión', 'Cumpleaños, disculpa, aniversario, primer día de trabajo. Cada uno pide una caja distinta.', '/img/bowl-aguacate.jpg', 'Equipo Aurora', '2026-07-15', 'Un aniversario pide Amanecer Romántico: fresas con crema y croissants rellenos hacen el trabajo emocional solos.

Un cumpleaños de oficina pide Cesta Campestre, porque alcanza para compartir y nadie queda mirando.

Una disculpa pide algo sencillo y bien escrito. Despertar Sencillo con una tarjeta larga funciona mejor que la caja más cara con dos líneas.

Un primer día de trabajo pide Zen Morning. Nadie quiere entrar a una reunión con azúcar encima.', 1);
INSERT OR IGNORE INTO posts (id, slug, title, excerpt, cover, author, date, body, published) VALUES ('b3', 'la-tarjeta-importa-mas-que-la-caja', 'La tarjeta importa más que la caja', 'Leemos miles de mensajes al año. Los que funcionan tienen una cosa en común: son específicos.', '/img/banano-rosa.jpg', 'Equipo Aurora', '2026-06-30', '«Feliz cumple, te quiero mucho» está bien. «Feliz cumple. Todavía me acuerdo del bus que perdimos en Villa de Leyva» es otra cosa.

La diferencia es la especificidad. Un detalle concreto convierte un mensaje genérico en algo que la persona guarda.

Tienes 300 caracteres en el configurador. Es suficiente para un recuerdo, un chiste interno o una frase que solo ustedes dos entienden. Úsalos.', 1);

INSERT OR IGNORE INTO settings (key, value) VALUES ('site', '{"brand":{"name":"Aurora Desayunos","tagline":"Desayunos sorpresa que llegan antes de que suene la alarma.","phone":"+57 300 000 0000","whatsapp":"573000000000","instagram":"@auroradesayunos","city":"Bogotá"},"banner":{"active":true,"text":"Entregamos de 6:00 a. m. a 11:00 a. m. en Bogotá. Recibimos pedidos hasta las 8:00 p. m. del día anterior."},"hero":{"title":"Llega antes que la alarma.","subtitle":"Se arman a las cuatro de la mañana y llegan a la puerta a la hora que elijas, con una tarjeta escrita a mano y flores si quieres.","ctaLabel":"Ver los desayunos","image":"/img/cama-lilas.jpg"},"sections":{"bestsellers":true,"catalog":true,"offers":true,"blog":true,"newsletter":true},"offers":{"active":true,"title":"Ofertas de la semana","note":"Precios vigentes hasta el domingo. Se aplican al agregar al carrito."},"delivery":{"fee":9000,"freeFrom":120000,"cities":["Bogotá","Chía","Cajicá","Soacha"],"slots":["06:00 – 07:00","07:00 – 08:00","08:00 – 09:00","09:00 – 10:00","10:00 – 11:00"],"cutoffNote":"Pedidos hasta las 8:00 p. m. del día anterior.","minLeadDays":1},"discountFirstOrder":10,"newsletter":{"title":"Una carta los viernes","body":"Escribimos una vez por semana: qué fruta está buena, qué caja nueva sale y de vez en cuando un descuento. Sin ruido."}}');
