-- GENERADO POR scripts/generate-copy-migration.mjs — no editar a mano.
-- Pasa el contenido ya cargado de voseo rioplatense a español colombiano.
-- El negocio es de Bogotá; «elegís / ponés / acá» sonaba importado.

UPDATE products SET tagline = 'El primer desayuno de la casa. Panqueques, jugo y una nota escrita a mano.', description = 'Nuestro desayuno de entrada: mini panqueques recién hechos con miel, jugo de naranja exprimido esa misma mañana y fruta cortada al momento. Va con cubiertos, servilleta de tela y una tarjeta que escribimos a mano con tu mensaje.', prep_note = 'Se arma la madrugada de la entrega. Pedidos hasta las 8:00 p. m. del día anterior.', includes = '[{"name":"Jugo de naranja natural","detail":"350 ml, exprimido el mismo día"},{"name":"Mini panqueques con miel","detail":"4 unidades"},{"name":"Fruta de temporada","detail":"corte del día"},{"name":"Mermelada y mantequilla","detail":"porción individual"},{"name":"Cubiertos y servilleta","detail":"incluidos"},{"name":"Tarjeta personalizada","detail":"escrita a mano con tu mensaje"}]' WHERE id = 'p1';
UPDATE products SET tagline = 'Yogurt griego, fresa, kiwi y galleta artesanal.', description = 'Para quien prefiere empezar liviano pero con azúcar honesta: yogurt griego con fresa y kiwi frescos, galleta artesanal horneada por una panadería del barrio y jugo de naranja.', prep_note = 'Viaja en frío hasta tu puerta.', includes = '[{"name":"Jugo de naranja natural","detail":"350 ml"},{"name":"Yogurt griego","detail":"vaso de 200 g"},{"name":"Fresas y kiwi","detail":"cortados al momento"},{"name":"Galleta artesanal","detail":"horneada el mismo día"}]' WHERE id = 'p2';
UPDATE products SET tagline = 'Jugo verde, tostadas de aguacate y frutos secos.', description = 'El desayuno de los que entrenan temprano. Jugo verde de espinaca, manzana y pepino; tostadas de pan de masa madre con aguacate; frutos secos y una tabla de fruta con kiwi, piña y arándanos.', prep_note = 'El jugo verde se hace 40 minutos antes de salir.', includes = '[{"name":"Jugo verde","detail":"espinaca, manzana y pepino · 350 ml"},{"name":"Tostadas de aguacate","detail":"2 unidades en masa madre"},{"name":"Frutos secos","detail":"almendra, marañón y nuez"},{"name":"Fruta fresca","detail":"kiwi, piña y arándanos"}]' WHERE id = 'p3';
UPDATE products SET tagline = 'Panqueques con chispas, brocheta de frutas y una sorpresa adentro.', description = 'Pensado para niños. Panqueques con toppings a elegir (miel, chispas de chocolate, rodajas de banano), brocheta de frutas, jugo, un yogurt pequeño y una sorpresa escondida en la caja.', prep_note = 'Cuéntanos la edad en las notas del pedido y ajustamos la sorpresa.', includes = '[{"name":"Panqueques","detail":"4 unidades"},{"name":"Toppings","detail":"miel, chispas de chocolate y banano en rodajas"},{"name":"Brocheta de frutas","detail":"2 unidades"},{"name":"Jugo","detail":"250 ml"},{"name":"Yogurt pequeño","detail":"150 g"},{"name":"Sorpresa","detail":"juguete o dulce sorpresa según edad"}]' WHERE id = 'p4';
UPDATE products SET tagline = 'Panadería, queso campesino, waffle integral y té.', description = 'Una cesta larga para desayunar sin prisa: pan integral, croissant, waffle integral, queso campesino, buñuelitos, fruta fresca con kiwi, fresa y mango, y una selección de tés.', prep_note = 'Va en cesta de mimbre que se queda con quien lo recibe.', includes = '[{"name":"Jugo natural","detail":"350 ml"},{"name":"Pan integral y croissant","detail":"de panadería local"},{"name":"Waffle integral","detail":"1 unidad"},{"name":"Queso campesino","detail":"porción de 150 g"},{"name":"Fruta fresca","detail":"kiwi, fresa y mango"},{"name":"Selección de tés","detail":"3 sobres"},{"name":"Buñuelitos","detail":"4 unidades"}]' WHERE id = 'p5';
UPDATE products SET tagline = 'Jugo de coco y jengibre, shot de limón, granola y cítricos.', description = 'La caja de los lunes. Jugo de coco con jengibre y limón, frutas cítricas, yogurt griego con granola, un shot de jengibre y limón, galleta integral de avena y bolitas de queso.', prep_note = 'El shot viaja aparte, en botella sellada.', includes = '[{"name":"Jugo de coco, jengibre y limón","detail":"350 ml"},{"name":"Frutas cítricas","detail":"naranja, mandarina y toronja"},{"name":"Yogurt griego con granola","detail":"200 g"},{"name":"Shot de jengibre y limón","detail":"60 ml"},{"name":"Galleta integral de avena","detail":"2 unidades"},{"name":"Bolitas de queso","detail":"4 unidades","needsReview":true}]' WHERE id = 'p6';
UPDATE products SET tagline = 'Fresas con crema, croissants rellenos de chocolate y jugo de frutos rojos.', description = 'El desayuno de aniversario. Jugo de frutos rojos y jugo de naranja, fresas con crema, croissants rellenos de chocolate, tabla de quesos y uvas verdes. Se puede pedir con globo y vela.', prep_note = 'Se entrega con tarjeta manuscrita. Globo y vela se agregan como adicionales.', includes = '[{"name":"Jugo de frutos rojos","detail":"350 ml"},{"name":"Jugo de naranja","detail":"350 ml"},{"name":"Fresas con crema","detail":"copa de 250 g"},{"name":"Croissants rellenos de chocolate","detail":"2 unidades"},{"name":"Tabla de quesos","detail":"3 quesos"},{"name":"Uvas verdes","detail":"racimo"}]' WHERE id = 'p7';
UPDATE products SET tagline = 'Dos jugos, tabla de galletas y quesos, avena con tocineta.', description = 'El más completo de la carta. Dos jugos, tabla de galletas y quesos, avena con tocineta, fruta fresca, uvas y arándanos, y bolitas de queso. Alcanza cómodo para dos personas.', prep_note = 'La avena viaja en termo para llegar caliente.', includes = '[{"name":"Dos jugos naturales","detail":"350 ml cada uno"},{"name":"Tabla de galletas y quesos","detail":"4 quesos"},{"name":"Avena con tocineta","detail":"porción caliente","needsReview":true},{"name":"Fruta fresca","detail":"corte del día"},{"name":"Uvas y arándanos","detail":"porción"},{"name":"Bolitas de queso","detail":"6 unidades","needsReview":true}]' WHERE id = 'p8';

UPDATE posts SET title = 'Cómo armamos una caja a las 4 de la mañana', excerpt = 'La fruta se corta a las 4:10. El jugo se exprime a las 4:40. La tarjeta se escribe de último, para que la tinta no se corra.', body = 'La cocina abre a las 3:40 a. m. No es romanticismo: un desayuno que sale a las 6:00 tiene que armarse en ese orden exacto o llega tibio.

Primero la fruta. Se corta entera, nunca la noche anterior, porque la piña suelta agua y moja la galleta. Después el pan: lo recogemos de la panadería de la esquina a las 4:30, todavía caliente.

El jugo va de último entre los líquidos. Exprimido a las 4:40, sellado a las 4:45, en frío hasta que sube al carro.

La tarjeta se escribe al final. Con tinta de gel, que seca rápido, y siempre a mano. Es lo primero que lee quien abre la caja.' WHERE id = 'b1';
UPDATE posts SET title = 'Qué desayuno regalar según la ocasión', excerpt = 'Cumpleaños, disculpa, aniversario, primer día de trabajo. Cada uno pide una caja distinta.', body = 'Un aniversario pide Amanecer Romántico: fresas con crema y croissants rellenos hacen el trabajo emocional solos.

Un cumpleaños de oficina pide Cesta Campestre, porque alcanza para compartir y nadie queda mirando.

Una disculpa pide algo sencillo y bien escrito. Despertar Sencillo con una tarjeta larga funciona mejor que la caja más cara con dos líneas.

Un primer día de trabajo pide Zen Morning. Nadie quiere entrar a una reunión con azúcar encima.' WHERE id = 'b2';
UPDATE posts SET title = 'La tarjeta importa más que la caja', excerpt = 'Leemos miles de mensajes al año. Los que funcionan tienen una cosa en común: son específicos.', body = '«Feliz cumple, te quiero mucho» está bien. «Feliz cumple. Todavía me acuerdo del bus que perdimos en Villa de Leyva» es otra cosa.

La diferencia es la especificidad. Un detalle concreto convierte un mensaje genérico en algo que la persona guarda.

Tienes 300 caracteres en el configurador. Es suficiente para un recuerdo, un chiste interno o una frase que solo ustedes dos entienden. Úsalos.' WHERE id = 'b3';

UPDATE settings SET value = '{"brand":{"name":"Aurora Desayunos","tagline":"Desayunos sorpresa que llegan antes de que suene la alarma.","phone":"+57 300 000 0000","whatsapp":"573000000000","instagram":"@auroradesayunos","city":"Bogotá"},"banner":{"active":true,"text":"Entregamos de 6:00 a. m. a 11:00 a. m. en Bogotá. Recibimos pedidos hasta las 8:00 p. m. del día anterior."},"hero":{"title":"Llega antes que la alarma.","subtitle":"Se arman a las cuatro de la mañana y llegan a la puerta a la hora que elijas, con una tarjeta escrita a mano y flores si quieres.","ctaLabel":"Ver los desayunos","image":"/img/cama-lilas.jpg"},"sections":{"bestsellers":true,"catalog":true,"offers":true,"blog":true,"newsletter":true},"offers":{"active":true,"title":"Ofertas de la semana","note":"Precios vigentes hasta el domingo. Se aplican al agregar al carrito."},"delivery":{"fee":9000,"freeFrom":120000,"cities":["Bogotá","Chía","Cajicá","Soacha"],"slots":["06:00 – 07:00","07:00 – 08:00","08:00 – 09:00","09:00 – 10:00","10:00 – 11:00"],"cutoffNote":"Pedidos hasta las 8:00 p. m. del día anterior.","minLeadDays":1},"discountFirstOrder":10,"newsletter":{"title":"Una carta los viernes","body":"Escribimos una vez por semana: qué fruta está buena, qué caja nueva sale y de vez en cuando un descuento. Sin ruido."}}' WHERE key = 'site';
